name: GitHub  Actions Demo
run-name: ${{ github.actor }} - is testing GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Report Triggering event
        run: echo "This workflow was triggered by the ${{ github.event_name }} event."
      - name: Data da execução
        run: ${{ github.event_date }} is the date of the execution